export const ADD_COUNTERS = "ADD_COUNTERS";
export const DELETE_COUNTERS = "DELETE_COUNTERS";
export const RESET_COUNTERS = "RESET_COUNTERS";
export const INCREMENT_COUNTERS = "INCREMENT_COUNTERS";
export const DECREMENT_COUNTERS = "DECREMENT_COUNTERS";
